name 'OpsWorks Demo'
maintainer 'DynaCode'
maintainer_email ''
license 'apache'
description 'Installs/Configures a Django-based server'
long_description 'Installs/Configures a Django-based server'
version '0.1'
